name: navigation
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^7.8.0
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  home:
    path: ../feature/home
  main:
    path: ../feature/main

dev_dependencies:
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  auto_route_generator: ^7.3.0
  build_runner: ^2.3.3