name: core_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  dropdown_button2: ^2.1.3
  extended_text: ^11.0.0
  calendar_date_picker2: ^0.5.2
  just_the_tooltip: ^0.0.12

  navigation:
    path: ../navigation
  core:
    path: ../core
  domain:
    path: ../domain


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true