name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.1.3
  extended_text: ^11.0.0
  calendar_date_picker2: ^0.5.2
  just_the_tooltip: ^0.0.12
  flutter_svg: ^2.0.7
  responsive_builder: ^0.7.0
  pull_to_refresh: ^2.0.0


  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  easy_image_viewer: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
